services:
  # -----------------------------------------------------------------
  # Serviço da API C# (Back-end)
  # -----------------------------------------------------------------
  api:
    build:
      # Usando a sua pasta BackEnd
      context: ./BackEnd
      dockerfile: Dockerfile
    
    ports:
      - "8000:8000"
      
    environment:
      - ASPNETCORE_URLS=http://+:8000
      - ASPNETCORE_ENVIRONMENT=Development 
    
    restart: always

  # -----------------------------------------------------------------
  # Serviço do Next.js (Front-end) - Configurado para Desenvolvimento
  # -----------------------------------------------------------------
  frontend:
    # 1. Caminho de Build
    build:
      # Onde o Docker encontra o Dockerfile e o código-fonte
      context: ./FrontEnd/blog-front-end
      dockerfile: Dockerfile
      
    ports:
      - "3000:3000"
      
    # 2. Caminho do Volume (ESSENCIAL PARA HOT-RELOAD)
    volumes:
      # CORRIGIDO: Este caminho deve ser EXATAMENTE a pasta que contém o package.json
      - ./FrontEnd/blog-front-end:/app
      # Volume anônimo para node_modules (boa prática)
      - /app/node_modules
      
    # Sobrescreve o CMD para rodar no modo de desenvolvimento
    command: npm run dev
      
    depends_on:
      - api
      
    environment:
      - NEXT_PUBLIC_API_URL=http://api:8000
      
    restart: always

